import { BikeColors } from "@constants/BikeColors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    pointerEvents: "box-none",
  },
  sheet: {
    backgroundColor: BikeColors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  handleWrap: {
    alignItems: "center",
    paddingVertical: 6,
  },
  handleTouchArea: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    marginBottom: 2,
  },
  handle: {
    width: 40,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#CBD5E1",
  },
  headerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  titleGroup: {
    flex: 1,
    gap: 2,
  },
  title: {
    fontSize: 16,
    fontWeight: "700",
    color: BikeColors.textPrimary,
  },
  subtitle: {
    fontSize: 13,
    fontWeight: "500",
    color: BikeColors.textSecondary,
  },
  compactActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  compactActionsWrap: {
    overflow: "hidden",
  },
  expandedSection: {
    gap: 0,
    overflow: "hidden",
  },
  compactChip: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  compactChipActive: {
    borderColor: "#BFDBFE",
    backgroundColor: "#DBEAFE",
  },
  compactChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: BikeColors.textPrimary,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: BikeColors.background,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  rowContent: {
    flex: 1,
    gap: 2,
  },
  rowLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: BikeColors.textSecondary,
  },
  rowValue: {
    fontSize: 14,
    fontWeight: "600",
    color: BikeColors.textPrimary,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  previewActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    alignItems: "center",
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  modeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  modeButtonActive: {
    backgroundColor: "#DBEAFE",
    borderColor: "#93C5FD",
  },
  modeButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: BikeColors.textPrimary,
  },
  smallButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  smallButtonActive: {
    backgroundColor: "#DBEAFE",
    borderColor: "#93C5FD",
  },
  smallButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: BikeColors.textPrimary,
  },
  primaryRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    alignItems: "center",
  },
  primaryButton: {
    flex: 1,
    height: 50,
    borderRadius: 24,
    backgroundColor: BikeColors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    height: 50,
    paddingHorizontal: 14,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: BikeColors.background,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  secondaryButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: BikeColors.textPrimary,
  },
  routeSummary: {
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  routeSummaryText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1E40AF",
  },
  routeActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  routeTextAction: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748B",
  },
  stationCard: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
    gap: 10,
  },
  stationInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  stationName: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: BikeColors.textPrimary,
  },
  stationMeta: {
    fontSize: 12,
    color: BikeColors.textSecondary,
  },
  stationAddress: {
    fontSize: 12,
    color: BikeColors.textSecondary,
  },
  detailButton: {
    alignSelf: "flex-start",
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#93C5FD",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  detailButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1D4ED8",
  },
});
