/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

export type CommandPayload = 'available' | 'booked' | 'reserved' | 'broken' | 'maintained' | 'unavailable' | 'book' | 'claim' | 'release' | 'start' | 'complete' | 'reserve' | 'cancel' | 'request' | string;
