/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ErrorDetailsIssuesItemReceived = unknown | null;
