/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetailsIssuesItemExpected } from './errorDetailsIssuesItemExpected';
import type { ErrorDetailsIssuesItemReceived } from './errorDetailsIssuesItemReceived';

export type ErrorDetailsIssuesItem = {
  /** Location of the invalid value */
  path: string;
  /** Why the value is invalid */
  message: string;
  /** Zod issue code */
  code?: string;
  /** @nullable */
  expected?: ErrorDetailsIssuesItemExpected;
  /** @nullable */
  received?: ErrorDetailsIssuesItemReceived;
};
