/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorMessage } from './errorMessage';
import type { ErrorDetails } from './errorDetails';

/**
 * Standard error payload returned by the IoT service.
 */
export interface ErrorResponse {
  error: ErrorMessage;
  details?: ErrorDetails;
}
