/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1Devices200ItemsItem } from './getV1Devices200ItemsItem';

export type GetV1Devices200 = {
  items: GetV1Devices200ItemsItem[];
};
