/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { IotStatusMessage } from './iotStatusMessage';

export type GetV1Devices200ItemsItem = {
  /** @minLength 1 */
  deviceId: string;
  status: IotStatusMessage;
};
