/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { HealthStatus } from './healthStatus';
import type { ServiceUptimeMs } from './serviceUptimeMs';
import type { HealthTimestamp } from './healthTimestamp';

export type GetV1Health200 = {
  status: HealthStatus;
  uptimeMs: ServiceUptimeMs;
  timestamp: HealthTimestamp;
};
