/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

export type IotBookingCommand = typeof IotBookingCommand[keyof typeof IotBookingCommand];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IotBookingCommand = {
  book: 'book',
  claim: 'claim',
  release: 'release',
} as const;
