/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

export type IotMaintenanceCommand = typeof IotMaintenanceCommand[keyof typeof IotMaintenanceCommand];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IotMaintenanceCommand = {
  start: 'start',
  complete: 'complete',
} as const;
