/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

export type IotStateCommand = typeof IotStateCommand[keyof typeof IotStateCommand];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IotStateCommand = {
  available: 'available',
  booked: 'booked',
  reserved: 'reserved',
  broken: 'broken',
  maintained: 'maintained',
  unavailable: 'unavailable',
} as const;
