/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Latest status message received from the device.
 */
export type IotStatusMessage = 'ESP32 online' | 'available' | 'booked' | 'reserved' | 'broken' | 'maintained' | 'unavailable' | string | string;
