/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { CommandDeviceId } from './commandDeviceId';
import type { CommandTopic } from './commandTopic';
import type { CommandPayload } from './commandPayload';

export type PostV1DevicesDeviceIdCommandsState202 = {
  deviceId: CommandDeviceId;
  topic: CommandTopic;
  payload: CommandPayload;
};
