/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { IotBookingCommand } from './iotBookingCommand';

export type PostV1DevicesDeviceIdCommandsBookingBody = {
  command: IotBookingCommand;
};
