/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * IoT Service API
 * HTTP contract for publishing IoT commands and querying device state.
 * OpenAPI spec version: 1.0.0
 */
import type { IotStatusCommand } from './iotStatusCommand';

export type PostV1DevicesDeviceIdCommandsStatusBody = {
  command?: IotStatusCommand;
};
