import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  ratingSection: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E3E8F2",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.045,
    shadowRadius: 6,
    elevation: 1,
  },
  ratingSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  ratingSectionDescription: {
    marginTop: 8,
    fontSize: 14,
    color: "#475569",
  },
  ratingForm: {
    marginTop: 12,
    gap: 12,
  },
  ratingPrompt: {
    fontSize: 13,
    fontWeight: "600",
    color: "#475569",
  },
  ratingStarsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  ratingStarButton: {
    padding: 4,
  },
  ratingErrorText: {
    color: "#F44336",
    fontSize: 12,
  },
  ratingReasonChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ratingHintText: {
    fontSize: 12,
    color: "#777",
  },
  ratingReasonChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D9E2F1",
    backgroundColor: "#F8FAFC",
    maxWidth: "100%",
  },
  ratingReasonChipSelected: {
    backgroundColor: "#EAF2FF",
    borderColor: "#3B82F6",
  },
  ratingReasonChipText: {
    fontSize: 13,
    color: "#334155",
  },
  ratingReasonChipTextSelected: {
    color: "#1D4ED8",
    fontWeight: "600",
  },
  ratingToggleButton: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#EEF3FF",
  },
  ratingToggleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#246BFD",
  },
  ratingCommentInput: {
    borderWidth: 1,
    borderColor: "#D9E2F1",
    borderRadius: 12,
    padding: 12,
    minHeight: 80,
    textAlignVertical: "top",
    fontSize: 14,
    color: "#1F2937",
  },
  ratingFormActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  ratingCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D9E2F1",
    alignItems: "center",
  },
  ratingCancelText: {
    fontSize: 14,
    color: "#475569",
    fontWeight: "600",
  },
  ratingSubmitButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#0066FF",
    paddingVertical: 12,
    borderRadius: 10,
  },
  ratingSubmitText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  ratingActionButton: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#0066FF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  ratingActionButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  ratingWindowHint: {
    marginTop: 8,
    fontSize: 12,
    color: "#64748B",
  },
  existingRatingContainer: {
    marginTop: 12,
    gap: 8,
  },
  ratingValueText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0066FF",
    marginTop: 4,
  },
  reasonsTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#475569",
    marginTop: 12,
    marginBottom: 4,
  },
  ratingTypeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  selectedReasonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  selectedReasonChip: {
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#0066FF",
    marginBottom: 4,
  },
  reasonHeader: {
    marginBottom: 4,
  },
  reasonTypeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#0066FF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  reasonMessageText: {
    fontSize: 13,
    color: "#333",
    fontWeight: "500",
  },
  selectedReasonText: {
    fontSize: 12,
    color: "#0066FF",
    fontWeight: "500",
  },
  existingCommentContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E6EAF2",
  },
  existingCommentLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  existingCommentText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
});
