import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  ratingSection: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  ratingSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  ratingSectionDescription: {
    marginTop: 8,
    fontSize: 14,
    color: "#555",
  },
  ratingForm: {
    marginTop: 12,
    gap: 12,
  },
  ratingPrompt: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  ratingStarsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  ratingStarButton: {
    padding: 4,
  },
  ratingErrorText: {
    color: "#F44336",
    fontSize: 12,
  },
  ratingReasonChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ratingHintText: {
    fontSize: 12,
    color: "#777",
  },
  ratingReasonChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#d0d7de",
    backgroundColor: "#fff",
  },
  ratingReasonChipSelected: {
    backgroundColor: "#0066FF",
    borderColor: "#0066FF",
  },
  ratingReasonChipText: {
    fontSize: 13,
    color: "#333",
  },
  ratingReasonChipTextSelected: {
    color: "#fff",
    fontWeight: "600",
  },
  ratingToggleButton: {
    alignSelf: "flex-start",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "#EEF3FF",
  },
  ratingToggleText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#246BFD",
  },
  ratingCommentInput: {
    borderWidth: 1,
    borderColor: "#d0d7de",
    borderRadius: 12,
    padding: 12,
    minHeight: 80,
    textAlignVertical: "top",
    fontSize: 14,
    color: "#333",
  },
  ratingFormActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  ratingCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d0d7de",
    alignItems: "center",
  },
  ratingCancelText: {
    fontSize: 14,
    color: "#555",
    fontWeight: "600",
  },
  ratingSubmitButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#0066FF",
    paddingVertical: 12,
    borderRadius: 10,
  },
  ratingSubmitText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  ratingActionButton: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#0066FF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  ratingActionButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  ratingWindowHint: {
    marginTop: 8,
    fontSize: 12,
    color: "#777",
  },
  existingRatingContainer: {
    marginTop: 12,
    gap: 8,
  },
  ratingValueText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0066FF",
    marginTop: 4,
  },
  reasonsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginTop: 12,
    marginBottom: 4,
  },
  ratingTypeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  selectedReasonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  selectedReasonChip: {
    backgroundColor: "#F0F7FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#0066FF",
    marginBottom: 4,
  },
  reasonHeader: {
    marginBottom: 4,
  },
  reasonTypeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#0066FF",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  reasonMessageText: {
    fontSize: 13,
    color: "#333",
    fontWeight: "500",
  },
  selectedReasonText: {
    fontSize: 12,
    color: "#0066FF",
    fontWeight: "500",
  },
  existingCommentContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#F8F9FA",
    borderRadius: 8,
  },
  existingCommentLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  existingCommentText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
});
