export const ENDPOINT = {
    AUTH: {
        LOGIN: "/auth/login",
        REGISTER: "/auth/register",
        LOGOUT: "/auth/logout",
        LOGOUT_ALL: "/auth/logout-all",
        RESEND_VERIFY_EMAIL: "/auth/verify-email/resend",
        SEND_VERIFY_EMAIL: "/auth/verify-email/send",
        VERIFY_EMAIL: "/auth/verify-email/otp",
        GET_ME: "/users/me",
        REFRESH_TOKEN: "/auth/refresh",
        CHANGE_PASSWORD: "/users/change-password",
        FORGOT_PASSWORD: "/auth/password/reset/send",
        VERIFY_FORGOT_PASSWORD: "/users/verify-forgot-password",
        RESET_PASSWORD: "/users/reset-password",
    },
    STATION : {
        BASE : "/stations",
        DETAIL : (stationId: string) => `/stations/${stationId}`,
        NEAR_BY : "/stations/nearby",
        STATION_BIKE_REVENUE: () => "/stations/bike-revenue",
        STATION_REVENUE: () => "/stations/revenue",
        STATION_NEAREST_AVAILABLE_BIKE: () =>
            "/stations/nearest-available-bike",
        SELECT_STATION :  
            "/admin/stations",
    },
    SUPPLIER : {
        BASE : "/suppliers",
        DETAIL : (id : string) => `/suppliers/${id}`,
        STATS : "/suppliers/stats",
        STATS_BIKE : (id : string) => `/suppliers/${id}/stats`,
    },
    USER : {
        BASE : "/users/manage-users/get-all",
        DETAIL : (id : string) => `/users/manage-users/${id}`,
        MANAGE_USER : "/users/manage",
        SEARCH_USER : "/users/manage-users/search",
        UPDATE : (id: string) => `/users/manage-users/${id}`, 
        STATS_ACTIVE_USER : "/users/manage-users/stats/active-users",
        STATS_TOP_RENTER : "/users/manage-users/stats/top-renters",
        DASHBOARD_USER_STATS : "/users/manage-users/dashboard-stats",
        STATS_USER : "/users/manage-users/stats",
        NEW_USER : "/users/manage-users/stats/new-users",
        RESET_PASSWORD : (id: string) => `/users/manage-users/admin-reset-password/${id}`,
        CREATE_USER : "/users/manage-users/create",
    },
    BIKE : {
        BASE : "/bikes",
        STATUS_COUNT : "/bikes/stats/status-counts",
        STATS_BIKE : (id : string) => `/bikes/${id}/stats/summary`,
        STATS_HIGHEST_REVENUE : "/bikes/stats/highest-revenue",
        ID : (id : string) => `/bikes/${id}`,
        RENTAL_HISTORY : (id : string) => `/bikes/${id}/rental-history`,
        ACTIVITY_STATS : (id : string) => `/bikes/${id}/activity-stats`,
        REPORT_BROKEN : (id : string) => `/bikes/report-broken/${id}`,
    },
    DASHBOARD : {
        STATS : "/stats/summary",
        STATIONS : "/dashboard/stations",
    },
    RENTAL : {
        BASE : "/admin/rentals",
        STAFF_ID : (id : string) => `/staff/rentals/${id}`,
        STAFF : "/staff/rentals",
        ID : (rentalId : string) => `/admin/rentals/${rentalId}`,
        GET_SUMMARY : "/rentals/stats/summary",
    },
    WALLET : {
        BASE : (userId : string) => `/admin/users/${userId}/wallet`,
        TRANSACTION : (userId : string) => `/admin/users/${userId}/wallet/transactions`,
    },
    RESERVATION : {
        BASE : "/admin/reservations",
        STAFF : "/staff/reservations",
        STAFF_ID : (id:string) => `/staff/reservations/${id}`,
        ID : (reservationId : string) => `/admin/reservations/${reservationId}`,
        OVERVIEW : "/reservations/stats/summary",
    },
    RATING : {
        BASE : "/admin/ratings",
        ID : (ratingID : string) => `/admin/ratings/${ratingID}`,
    },
    AGENCY : {
        BASE : "/admin/agencies",
        ID : (id : string) => `/admin/agencies/${id}`,
        STATUS : (id : string) => `/admin/agencies/${id}/status`,
        STATS : (id:string) => `/admin/agencies/${id}/stats`,
    },
    AGENCY_REQUEST : {
        BASE : "/admin/agency-requests",
        ID : (id : string) => `/admin/agency-requests/${id}`,
        APPROVE : (id:string) => `/admin/agency-requests/${id}/approve`,
        REJECT : (id:string) => `/admin/agency-requests/${id}/reject`,
        CANCEL : (id:string) => `/admin/agency-requests/${id}/cancel`,
    }

} as const;
