export const MESSAGE = {
  LOGIN_SUCCESS: "Đăng nhập thành công",
  LOGIN_NOT_SUCCESS: "Đăng nhập không thành công",
  WELCOME_BACK: "Chào mừng bạn trở lại!",
  LOGOUT_SUCCESS: "Đăng xuất thành công",
  LOGOUT_FAIL: "Đăng xuất không thành công",
  REGISTER_SUCCESS: "Đăng ký thành công",
  REGISTER_NOT_SUCCESS: "Đăng ký không thành công",
  CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
  CHANGE_PASSWORD_ERROR: "Lỗi khi đổi mật khẩu",
  ERROR_IN_CHANGE_PASSWORD: "Lỗi khi đang thay đổi mật khẩu",
  UPDATE_PROFILE_SUCCESS: "Cập nhật thông tin cá nhân thành công",
  UPDATE_PROFILE_FAILED: "Cập nhật thông tin cá nhân không thành công",
  FORGOT_PASSWORD_SUCCESS:
    "Yêu cầu đặt lại mật khẩu thành công. Vui lòng kiểm tra email của bạn.",
  FORGOT_PASSWORD_FAILED: "Lỗi khi yêu cầu đặt lại mật khẩu.",
  RESET_PASSWORD_SUCCESS:
    "Đặt lại mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.",
  RESET_PASSWORD_FAILED: "Lỗi khi đặt lại mật khẩu.",
  EMAIL_VERIFY_SUCCESS: "Xác minh email thành công.",
  EMAIL_VERIFY_ERROR: "Lỗi khi xác minh email.",
  RESEND_VERIFY_EMAIL_SUCCESS:
    "Gửi lại email xác minh thành công. Vui lòng kiểm tra hộp thư đến của bạn.",
  RESEND_VERIFY_EMAIL_FAILED: "Lỗi khi gửi lại email xác minh.",
  TOKEN_EXPIRED: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  OTP_EXPIRED: "Mã OTP đã hết hạn. Vui lòng yêu cầu mã mới.",
  ERROR_IN_LOGOUT: "Lỗi khi đăng xuất",
  CREATE_BIKE_SUCCESS: "Tạo xe đạp thành công",
  CREATE_BIKE_FAILED: "Lỗi khi tạo xe đạp",
  UPDATE_BIKE_SUCCESS: "Cập nhật xe đạp thành công",
  UPDATE_BIKE_FAILED: "Lỗi khi cập nhật xe đạp",
  DELETE_BIKE_SUCCESS: "Xóa xe đạp thành công",
  DELETE_BIKE_FAILED: "Lỗi khi xóa xe đạp",
  REPORT_BIKE_SUCCESS: "Báo cáo xe đạp thành công",
  REPORT_BIKE_FAILED: "Lỗi khi báo cáo xe đạp",
  UPDATE_REFUND_REQUEST_SUCCESS: "Cập nhật yêu cầu hoàn tiền thành công",
  UPDATE_REFUND_REQUEST_FAILED: "Lỗi khi cập nhật yêu cầu hoàn tiền",
  UPDATE_RENTAL_BIKE_SUCCESS: "Phiên thuê xe đã được cập nhật thành công",
  UPDATE_RENTAL_FAILED: "Lỗi khi cập nhật phiên thuê xe",
  END_RENTAL_SUCCESS: "Kết thúc phiên thuê xe thành công",
  END_RENTAL_FAILED: "Kết thúc phiên thuê xe thất bại",
  UPDATE_REPORT_SUCCESS: "Cập nhật báo cáo thành công",
  UPDATE_REPORT_FAILED: "Lỗi khi cập nhật báo cáo",
  RESOLVE_REPORT_SUCCESS: "Xử lý báo cáo thành công",
  RESOLVE_REPORT_FAILED: "Lỗi khi xử lý báo cáo",
  ASSIGN_SOS_GUEST_SUCCESS: "Yêu cầu cứu hộ đã được phân công thành công",
  ASSIGN_SOS_GUEST_FAILED: "Yêu cầu cứu hộ đã được phân công thất bại",
  CONFIRM_SOS_GUEST_SUCCESS: "Xác nhận yêu cầu cứu hộ thành công",
  CONFIRM_SOS_GUEST_FAILED: "Xác nhận yêu cầu cứu hộ thất bại",
  RESOLVE_SOS_SUCCESS:"Giải quyết cứu hộ thành công",
  RESOLVE_SOS_FAILED:"Giải quyết cứu hộ thất bại",
  CREATE_SOS_SUCCESS:"Tạo phiên thuê xe thành công",
  CREATE_SOS_FAILED:"Tạo phiên thuê xe thất bại",
  CANCEL_SOS_SUCCESS:"Hủy phiên thuê xe thành công",
  CANCEL_SOS_FAILED:"Hủy phiên thuê xe thất bại",
  CREATE_STATION_SUCCESS:"Tạo trạm thành công",
  CREATE_STATION_FAILED:"Tạo trạm thất bại",
  DELETE_STATION_SUCCESS:"Xóa trạm thành công",
  DELETE_STATION_FAILED:"Xóa trạm không thành công",
  UPDATE_STATION_SUCCESS:"Cập nhật trạm thành công",
  UPDATE_STATION_FAILED:"Cập nhật trạm thất bại", 
  
};