export const MESSAGE = {
    LOGIN_SUCCESS: "Đăng nhập thành công",
    LOGIN_NOT_SUCCESS: "Đăng nhập không thành công",
    WELCOME_BACK: "Chào mừng bạn trở lại!",
    LOGOUT_SUCCESS: "Đăng xuất thành công",
    LOGOUT_FAIL: "Đăng xuất không thành công",
    REGISTER_SUCCESS: "Đăng ký thành công",
    REGISTER_NOT_SUCCESS: "Đăng ký không thành công",
    CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
    CHANGE_PASSWORD_ERROR: "Lỗi khi đổi mật khẩu",
    ERROR_IN_CHANGE_PASSWORD: "Lỗi khi đang thay đổi mật khẩu",
    UPDATE_PROFILE_SUCCESS: "Cập nhật thông tin cá nhân thành công",
    UPDATE_PROFILE_FAILED: "Cập nhật thông tin cá nhân không thành công",
    FORGOT_PASSWORD_SUCCESS: "Yêu cầu đặt lại mật khẩu thành công. Vui lòng kiểm tra email của bạn.",
    FORGOT_PASSWORD_FAILED: "Lỗi khi yêu cầu đặt lại mật khẩu.",
    RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công. Bạn có thể đăng nhập bằng mật khẩu mới.",
    RESET_PASSWORD_FAILED: "Lỗi khi đặt lại mật khẩu.",
    EMAIL_VERIFY_SUCCESS: "Xác minh email thành công.",
    EMAIL_VERIFY_ERROR: "Lỗi khi xác minh email.",
    RESEND_VERIFY_EMAIL_SUCCESS: "Gửi lại email xác minh thành công. Vui lòng kiểm tra hộp thư đến của bạn.",
    RESEND_VERIFY_EMAIL_FAILED: "Lỗi khi gửi lại email xác minh.",
    TOKEN_EXPIRED: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    OTP_EXPIRED: "Mã OTP đã hết hạn. Vui lòng yêu cầu mã mới.",
    ERROR_IN_LOGOUT: "Lỗi khi đăng xuất",
}