
openapi: 3.0.0
info:
  title: MeBike API
  version: 1.0.0
  description: API documentation for the MeBike project.
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths: {}
