import * as mutations from "./mutations";
import * as queries from "./queries";

export {
  agencyApproveBikeSwapRequest,
  agencyRejectBikeSwapRequest,
  approveBikeSwapRequest,
  cancelMyReturnSlot,
  confirmRentalReturnByOperator,
  createMyReturnSlot,
  createRental,
  createRentalFromSOS,
  endRentalByAdmin,
  operatorApproveBikeSwapRequest,
  operatorRejectBikeSwapRequest,
  rejectBikeSwapRequest,
  requestBikeSwap,
  staffCreateRental,
  updateRental,
} from "./mutations";

export {
  adminGetBikeSwapRequests,
  adminGetRental,
  adminListBikeSwapRequests,
  adminListRentals,
  agencyGetBikeSwapRequests,
  agencyGetRental,
  agencyListBikeSwapRequests,
  agencyListRentals,
  getActiveRentalsByPhone,
  getAllRentals,
  getDashboardSummary,
  getMyBikeSwapRequest,
  getMyBikeSwapRequests,
  getMyCurrentRentals,
  getMyCurrentReturnSlot,
  getMyRental,
  getMyRentalBillingDetail,
  getMyRentalBillingPreview,
  getMyRentalCounts,
  getMyRentals,
  getRental,
  getRentalRevenue,
  getRentalsByUser,
  getRentalStatsSummary,
  getRentalSummary,
  getStationActivity,
  operatorGetBikeSwapRequests,
  operatorListBikeSwapRequests,
  staffGetBikeSwapRequests,
  staffGetRental,
  staffListBikeSwapRequests,
  staffListRentals,
} from "./queries";

export const rentalsRoutes = {
  ...queries,
  ...mutations,
} as const;
